echo 'cleaning node_modules';
rm -rf node_modules
echo 'cleaning core';
rm -rf packages/core/node_modules
rm -rf packages/core/lib
rm -rf packages/core/coverage
echo 'cleaning async';
rm -rf packages/async/node_modules
rm -rf packages/async/lib
rm -rf packages/async/coverage
echo 'cleaning react';
rm -rf packages/react/node_modules
rm -rf packages/react/lib
rm -rf packages/react/coverage
echo 'cleaning docs';
rm -rf packages/docs/node_modules
rm -rf packages/docs/build
rm -rf packages/docs/coverage
echo 'done!! :)';
